In [32]:
import numpy as np
k = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(k)
k[:]=np.maximum(k+np.random.rand(*k.shape)-.5,0)
print(k)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 2 3]
 [3 4 5]
 [6 7 8]]


In [23]:
DNA_SIZE = 1             # DNA (real number)
DNA_BOUND = [-10, 10]       # solution upper and lower bounds
N_GENERATIONS = 200
POP_SIZE = 1000           # population size
N_KID = 500               # n kids per generation

kids = {'DNA': np.empty((n_kid, DNA_SIZE))}

[[1 2 3]
 [4 5 6]
 [7 8 9]]
